name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish

      - name: Compress artifact
        if: ${{ github.event_name != 'pull_request' }}
        run: tar -zcf workshop.tar.gz -C ./bin/Debug/net6.0/publish/ .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: workshop.tar.gz
          path: workshop.tar.gz

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.4
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: workshop.tar.gz

      - name: Extract artifact
        run: tar -xf workshop.tar.gz

      - name: Azure App Service Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: app-workshop-PauPat
          app-settings-json: ${{ secrets.APPSETTINGS_JSON }}

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-workshop-PauPat # Should match with app name in azure

      - name: Logout Azure
        run: |
          az logout
